// packages/react/src/lib/types/html.ts
import type {
  AnchorHTMLAttributes as ReactAnchorHTMLAttributes,
  ButtonHTMLAttributes as ReactButtonHTMLAttributes,
  ImgHTMLAttributes as ReactImgHTMLAttributes,
} from "react";

export type AnchorHTMLAttributes = Pick<
  ReactAnchorHTMLAttributes<HTMLAnchorElement>,
  | "download"
  | "href"
  | "hrefLang"
  | "media"
  | "ping"
  | "rel"
  | "target"
  | "type"
  | "referrerPolicy"
>;

export type ButtonHTMLAttributes = Pick<
  ReactButtonHTMLAttributes<HTMLButtonElement>,
  | "autoFocus"
  | "disabled"
  | "form"
  | "formAction"
  | "formEncType"
  | "formMethod"
  | "formNoValidate"
  | "formTarget"
  | "name"
  | "type"
>;

export type ImgHTMLAttributes = Pick<
  ReactImgHTMLAttributes<HTMLImageElement>,
  | "alt"
  | "crossOrigin"
  | "decoding"
  | "height"
  | "loading"
  | "referrerPolicy"
  | "sizes"
  | "src"
  | "srcSet"
  | "useMap"
  | "width"
>;

// packages/solid/src/lib/types/html.ts
import type { JSX } from "solid-js";

export type AnchorHTMLAttributes = Pick<
  Partial<JSX.AnchorHTMLAttributes<HTMLAnchorElement>>,
  "href" | "ping" | "rel" | "target" | "type" | "referrerPolicy"
>;

export type ButtonHTMLAttributes = Pick<
  Partial<HTMLButtonElement>,
  | "autofocus"
  | "disabled"
  | "form"
  | "formAction"
  | "formEnctype"
  | "formMethod"
  | "formNoValidate"
  | "formTarget"
  | "name"
  | "type"
>;

export type ImgHTMLAttributes = Pick<
  Partial<HTMLImageElement>,
  | "alt"
  | "decoding"
  | "height"
  | "loading"
  | "referrerPolicy"
  | "sizes"
  | "src"
  | "srcset"
  | "useMap"
  | "width"
> & {
  crossOrigin?: JSX.HTMLCrossorigin;
  referrerPolicy?: JSX.HTMLReferrerPolicy;
};
