// packages/react/src/lib/components/ui/container/container.tsx
import { ui as theme } from "@iueev/core/theme";
import { cv } from "@iueev/core/utils";

import type { ContainerTheme } from "./container.types";

export interface ContainerProps extends React.ComponentProps<"div"> {
  ui?: ContainerTheme["slots"];
}

function Container({ className, ui: overrides, ...props }: ContainerProps) {
  const ui = cv(theme.container);
  return (
    <div
      className={ui({ className: [overrides?.base, className] })}
      data-scope="container"
      {...props}
    />
  );
}

export default Container;

// packages/solid/src/lib/components/ui/container/container.tsx
import { type ComponentProps, splitProps } from "solid-js";

import { ui as theme } from "@iueev/core/theme";
import { cv } from "@iueev/core/utils";

import type { ContainerTheme } from "./container.types";

export interface ContainerProps extends ComponentProps<"div"> {
  ui?: ContainerTheme["slots"];
}

function Container(props: ContainerProps) {
  const [{ children, ui: overrides }, attrs] = splitProps(props, [
    "children",
    "ui",
  ]);
  const ui = cv(theme.container);
  return (
    <div
      class={ui({ className: [overrides?.base, props.class] })}
      data-scope="container"
      {...attrs}
    >
      {children}
    </div>
  );
}

export default Container;
