// packages/svelte/src/lib/components/ui/container/container.svelte
<script lang="ts">
  import { Factory } from "#build/ui/components";
  import { cx } from "#build/ui/utils";

  import type { ContainerProps } from "./container.types";

  let {
    as = "div",
    children,
    class: className,
    ref = $bindable(null),
    ui,
    ...attrs
  }: ContainerProps = $props();
</script>

<Factory
  {...attrs}
  {as}
  class={cx(ui?.base, className)}
  data-scope="container"
  {ref}
>
  {@render children?.()}
</Factory>

// packages/solid/src/lib/components/ui/container/container.tsx
import { type Component, splitProps } from "solid-js";

import { Factory } from "#build/ui/components";
import { cx } from "#build/ui/utils";

import type { ContainerProps } from "./container.types";

const Container: Component<ContainerProps> = (props) => {
  const [{ children, ui }, attrs] = splitProps(props, ["children", "ui"]);
  return (
    <Factory.div
      {...attrs}
      class={cx(ui?.base, attrs.class)}
      data-scope="container"
    >
      {children}
    </Factory.div>
  );
};

export default Container;
