// packages/solid/src/lib/elements/link/link-base.tsx
import { type Component, type JSX, splitProps } from "solid-js";

import { isArray } from "radashi";

import { Factory } from "@/elements/factory";

import type { LinkBaseProps } from "./link.types";

const LinkBase: Component<LinkBaseProps & { children: JSX.Element }> = (
  props
) => {
  const [{ children, href, raw, ...rootProps }, attrs] = splitProps(props, [
    "active",
    "children",
    "disabled",
    "href",
    "isExternal",
    "onClick",
    "raw",
    "rel",
    "target",
    "type",
  ]);

  const onClickWrapper = (e: MouseEvent) => {
    if (rootProps.disabled) {
      e.preventDefault();
      e.stopPropagation();
      return;
    }

    if (rootProps.onClick) {
      for (const handler of isArray(rootProps.onClick)
        ? rootProps.onClick
        : [rootProps.onClick]) {
        handler(e as any);
      }
    }
  };

  if (href) {
    return (
      <Factory.a
        aria-disabled={rootProps.disabled ? true : undefined}
        data-active={rootProps.active ? "true" : undefined}
        data-scope={raw ? undefined : "link"}
        href={rootProps.disabled ? undefined : href}
        onClick={onClickWrapper}
        rel={rootProps.rel as string}
        role={rootProps.disabled ? "link" : undefined}
        tabIndex={rootProps.disabled ? -1 : undefined}
        target={rootProps.target as string}
        {...attrs}
      >
        {children}
      </Factory.a>
    );
  }

  return (
    <Factory.button
      data-active={rootProps.active ? "true" : undefined}
      data-scope={raw ? undefined : "link"}
      disabled={rootProps.disabled}
      onClick={onClickWrapper}
      type={rootProps.type ?? "button"}
      {...(attrs as any)}
    >
      {children}
    </Factory.button>
  );
};

export default LinkBase;

// packages/react/src/lib/elements/link/link-base.tsx
import { forwardRef, type MouseEvent, useCallback } from "react";

import { isArray } from "radashi";

import { Factory } from "@/elements/factory";

import type { LinkBaseProps } from "./link.types";

const LinkBase = forwardRef<
  HTMLAnchorElement | HTMLButtonElement,
  LinkBaseProps & { children: React.ReactNode }
>(
  (
    {
      active,
      children,
      disabled,
      href,
      isExternal,
      onClick,
      raw,
      rel,
      target,
      type = "button",
      ...attrs
    },
    ref
  ) => {
    const onClickWrapper = useCallback(
      (e: MouseEvent<HTMLAnchorElement | HTMLButtonElement>) => {
        if (disabled) {
          e.preventDefault();
          e.stopPropagation();
          return;
        }

        if (onClick) {
          for (const handler of isArray(onClick) ? onClick : [onClick]) {
            handler(e as any);
          }
        }
      },
      [disabled, onClick]
    );

    if (href) {
      return (
        <Factory.a
          aria-disabled={disabled ? true : undefined}
          data-active={active ? "true" : undefined}
          data-scope={raw ? undefined : "link"}
          href={disabled ? undefined : href}
          onClick={onClickWrapper}
          ref={ref as any}
          rel={rel as string}
          role={disabled ? "link" : undefined}
          tabIndex={disabled ? -1 : undefined}
          target={target as string}
          {...attrs}
        >
          {children}
        </Factory.a>
      );
    }

    return (
      <Factory.button
        data-active={active ? "true" : undefined}
        data-scope={raw ? undefined : "link"}
        disabled={disabled}
        onClick={onClickWrapper}
        ref={ref as any}
        type={type}
        {...attrs}
      >
        {children}
      </Factory.button>
    );
  }
);

LinkBase.displayName = "LinkBase";

export default LinkBase;
