// packages/vue/src/lib/providers/locale/locale.vue
<script lang="ts" setup>
  import { toRef } from "vue";

  import type { LocaleProviderProps } from "./locale.types";
  import { LocaleContextProvider } from "./use-locale-context";

  const props = defineProps<LocaleProviderProps>();

  const locale = toRef(() => props.value!);
  LocaleContextProvider(locale);
</script>

<template>
  <slot />
</template>

// packages/react/src/lib/providers/locale/locale.tsx
"use client";

import type { LocaleProviderProps } from "./locale.types";
import { LocaleContextProvider } from "./use-locale-context";

function LocaleProvider({ children, value }: LocaleProviderProps) {
  return (
    <LocaleContextProvider value={value!}>{children}</LocaleContextProvider>
  );
}

export default LocaleProvider;
