// packages/solid/src/lib/providers/locale/locale.tsx
import { createMemo } from "solid-js";

import type { LocaleProviderProps } from "./locale.types";
import { LocaleContextProvider } from "./use-locale-context";

function LocaleProvider(props: LocaleProviderProps) {
  const context = createMemo(() => props.value!);
  return (
    <LocaleContextProvider value={context}>
      {props.children}
    </LocaleContextProvider>
  );
}

export default LocaleProvider;

// packages/react/src/lib/providers/locale/locale.tsx
"use client";

import type { LocaleProviderProps } from "./locale.types";
import { LocaleContextProvider } from "./use-locale-context";

function LocaleProvider({ children, value }: LocaleProviderProps) {
  return (
    <LocaleContextProvider value={value!}>{children}</LocaleContextProvider>
  );
}

export default LocaleProvider;
