// packages/solid/src/lib/providers/color-mode/examples/basic.tsx
import { ColorModeProvider } from "@veehance/solid/color-mode";
import { EnvironmentProvider } from "@veehance/solid/environment";

import Usage from "./usage.js";

export default () => (
  <EnvironmentProvider>
    <ColorModeProvider>
      <Usage />
    </ColorModeProvider>
  </EnvironmentProvider>
);

// packages/svelte/src/lib/providers/color-mode/examples/basic.svelte
<script lang="ts">
  import { ColorModeProvider } from "@veehance/svelte/color-mode";
  import { EnvironmentProvider } from "@veehance/svelte/environment";

  import Usage from "./usage.svelte";
</script>

<EnvironmentProvider>
  <ColorModeProvider>
    <Usage />
  </ColorModeProvider>
</EnvironmentProvider>
