// packages/react/src/lib/providers/color-mode/examples/setup.tsx
import { ColorModeProvider } from "@veehance/react/color-mode";
import { EnvironmentProvider } from "@veehance/react/environment";

import Frame from "react-frame-component";

export default () => {
  return (
    <Frame title="IFrame Context">
      <EnvironmentProvider>
        <ColorModeProvider>{/* Your App */}</ColorModeProvider>
      </EnvironmentProvider>
    </Frame>
  );
};

// packages/svelte/src/lib/providers/color-mode/examples/setup.svelte
<script lang="ts">
  import { ColorModeProvider } from "@veehance/svelte/color-mode";
  import { EnvironmentProvider } from "@veehance/svelte/environment";
</script>

<iframe title="IFrame Context">
  <EnvironmentProvider>
    <ColorModeProvider><!-- Your App --></ColorModeProvider>
  </EnvironmentProvider>
</iframe>
