// packages/vue/src/lib/providers/color-mode/examples/setup.vue
<script lang="ts" setup>
  import { ColorModeProvider } from "@veehance/vue/color-mode";
  import { EnvironmentProvider } from "@veehance/vue/environment";
</script>

<template>
  <iframe title="IFrame Context">
    <EnvironmentProvider>
      <ColorModeProvider><!-- Your App --></ColorModeProvider>
    </EnvironmentProvider>
  </iframe>
</template>

// packages/svelte/src/lib/providers/color-mode/examples/setup.svelte
<script lang="ts">
  import { ColorModeProvider } from "@veehance/svelte/color-mode";
  import { EnvironmentProvider } from "@veehance/svelte/environment";
</script>

<iframe title="IFrame Context">
  <EnvironmentProvider>
    <ColorModeProvider><!-- Your App --></ColorModeProvider>
  </EnvironmentProvider>
</iframe>
