// packages/vue/src/lib/providers/color-mode/examples/basic.vue
<script lang="ts" setup>
  import { ColorModeProvider } from "@veehance/vue/color-mode";
  import { EnvironmentProvider } from "@veehance/vue/environment";

  import Usage from "./usage.vue";
</script>

<template>
  <EnvironmentProvider>
    <ColorModeProvider>
      <Usage />
    </ColorModeProvider>
  </EnvironmentProvider>
</template>

// packages/react/src/lib/providers/color-mode/examples/basic.tsx
import { ColorModeProvider } from "@veehance/react/color-mode";
import { EnvironmentProvider } from "@veehance/react/environment";

import Usage from "./usage.js";

export default () => (
  <EnvironmentProvider>
    <ColorModeProvider>
      <Usage />
    </ColorModeProvider>
  </EnvironmentProvider>
);
