// packages/svelte/src/lib/components/ui/main/main.svelte
<script lang="ts">
  import { Factory } from "#build/ui/components";
  import { cx } from "#build/ui/utils";

  import type { MainProps } from "./main.types";

  let {
    as = "main",
    children,
    class: className,
    ref = $bindable(null),
    ui,
    ...attrs
  }: MainProps = $props();
</script>

<Factory
  {...attrs}
  {as}
  class={cx(ui?.base, className)}
  data-scope="main"
  {ref}
>
  {@render children?.()}
</Factory>

// packages/solid/src/lib/components/ui/main/main.tsx
import { type Component, splitProps } from "solid-js";

import { Factory } from "#build/ui/components";
import { cx } from "#build/ui/utils";

import type { MainProps } from "./main.types";

const Main: Component<MainProps> = (props) => {
  const [{ children, ui }, attrs] = splitProps(props, ["children", "ui"]);
  return (
    <Factory.main
      {...attrs}
      class={cx(ui?.base, attrs.class)}
      data-scope="main"
    >
      {children}
    </Factory.main>
  );
};

export default Main;
