// packages/svelte/src/lib/components/color-mode/image/image.svelte
<script lang="ts">
  import { Image } from "#build/ui/components";
  import { cc, cn } from "#build/ui/utils";

  import type { ColorModeImageProps } from "./image.types";

  let {
    class: className,
    light,
    dark,
    ref = $bindable(null),
    ui,
    ...attrs
  }: ColorModeImageProps = $props();
</script>

<Image
  class={cn(cc('dark:hidden'), ui?.base, className)}
  {ref}
  src={light}
  {...attrs}
/>
<Image
  class={cn(cc('hidden dark:inline-block'), ui?.base, className)}
  {ref}
  src={dark}
  {...attrs}
/>

// packages/solid/src/lib/components/color-mode/image/image.tsx
import { type Component, splitProps } from "solid-js";

import { Image } from "#build/ui/components";
import { cc, cx } from "#build/ui/utils";

import type { ColorModeImageProps } from "./image.types";

const ColorModeImage: Component<ColorModeImageProps> = (props) => {
  const [{ dark, light, ui }, attrs] = splitProps(props, [
    "dark",
    "light",
    "ui",
  ]);
  return (
    <>
      <Image
        {...attrs}
        class={cx(cc("dark:hidden"), ui?.base, attrs.class)}
        src={light}
      />
      <Image
        {...attrs}
        class={cx(cc(["hidden dark:inline-block"]), ui?.base, attrs.class)}
        src={dark}
      />
    </>
  );
};

export default ColorModeImage;
