// packages/react/src/base/router/link/link.tsx
import { forwardRef } from "react";

import { cx } from "#build/ui/utils";

import { hasProtocol } from "ufo";

import { Dynamic } from "@/utils/dynamic";

import type { LinkProps } from "./link.types";
import LinkBase from "./link-base";

const Link = forwardRef<HTMLAnchorElement | HTMLButtonElement, LinkProps>(
  (
    {
      active,
      activeClass,
      ariaCurrentValue = "page",
      children,
      className,
      custom,
      disabled,
      external,
      href,
      inactiveClass,
      noRel,
      raw,
      rel,
      target,
      to,
      type = "button",
      ui,
      ...attrs
    },
    ref
  ) => {
    const resolvedHref = to ?? href;

    const isExternal =
      target === "_blank" ||
      external ||
      (!!resolvedHref && hasProtocol(resolvedHref, { acceptRelative: true }));

    const resolvedRel = noRel
      ? undefined
      : (rel ?? (isExternal ? "noopener noreferrer" : undefined));

    const isActive = active ?? false;

    const linkClass = raw
      ? cx(className, isActive ? activeClass : inactiveClass)
      : cx(ui?.base, className, isActive ? activeClass : inactiveClass);

    if (custom) {
      return (
        <Dynamic
          active={isActive}
          disabled={disabled}
          href={resolvedHref}
          isExternal={isExternal}
          raw={raw}
          ref={ref}
          rel={resolvedRel}
          target={target ?? (isExternal ? "_blank" : undefined)}
          type={type}
          {...attrs}
        >
          {children}
        </Dynamic>
      );
    }

    return (
      <LinkBase
        className={linkClass}
        disabled={disabled}
        href={resolvedHref}
        isExternal={isExternal}
        raw={raw}
        ref={ref}
        rel={resolvedRel}
        target={target ?? (isExternal ? "_blank" : undefined)}
        type={type}
        {...attrs}
      >
        <Dynamic {...attrs} active={isActive}>
          {children}
        </Dynamic>
      </LinkBase>
    );
  }
);

Link.displayName = "Link";

export default Link;

// packages/solid/src/base/inertia/link/link.tsx
import { type Component, splitProps } from "solid-js";

import { cx } from "#build/ui/utils";

import { hasProtocol } from "ufo";

import { Dynamic } from "@/utils/dynamic";

import type { LinkProps } from "./link.types";
import LinkBase from "./link-base";

const Link: Component<LinkProps> = (props) => {
  const [
    {
      ariaCurrentValue = "page",
      children,
      custom,
      href,
      raw,
      to,
      type = "button",
      ui,
      ...rootProps
    },
    attrs,
  ] = splitProps(props, [
    "active",
    "activeClass",
    "ariaCurrentValue",
    "children",
    "custom",
    "disabled",
    "external",
    "href",
    "inactiveClass",
    "noRel",
    "raw",
    "rel",
    "target",
    "to",
    "type",
    "ui",
  ]);

  const resolvedHref = to ?? href;

  const isExternal =
    rootProps.target === "_blank" ||
    rootProps.external ||
    (!!resolvedHref && hasProtocol(resolvedHref, { acceptRelative: true }));

  const resolvedRel = rootProps.noRel
    ? undefined
    : (rootProps.rel ?? (isExternal ? "noopener noreferrer" : undefined));

  const isActive = rootProps.active ?? false;

  const linkClass = raw
    ? cx(
        attrs.class,
        isActive ? rootProps.activeClass : rootProps.inactiveClass
      )
    : cx(
        ui?.base,
        attrs.class,
        isActive ? rootProps.activeClass : rootProps.inactiveClass
      );

  if (custom) {
    return (
      <Dynamic
        active={isActive}
        ariaCurrentValue={ariaCurrentValue}
        disabled={rootProps.disabled}
        href={resolvedHref}
        isExternal={isExternal}
        raw={raw}
        rel={resolvedRel}
        target={rootProps.target ?? (isExternal ? "_blank" : undefined)}
        type={type}
        {...attrs}
      >
        {children}
      </Dynamic>
    );
  }

  return (
    <LinkBase
      class={linkClass}
      disabled={rootProps.disabled}
      href={resolvedHref}
      isExternal={isExternal}
      raw={raw}
      rel={resolvedRel}
      target={rootProps.target ?? (isExternal ? "_blank" : undefined)}
      type={type}
      {...attrs}
    >
      <Dynamic active={isActive}>{children}</Dynamic>
    </LinkBase>
  );
};

export default Link;
