// packages/svelte/src/lib/elements/link/link.svelte
<script lang="ts">
  import { cx } from "#build/ui/utils";

  import { hasProtocol } from "ufo";

  import type { LinkProps } from "./link.types";
  import LinkBase from "./link-base.svelte";

  let {
    active,
    activeClass,
    ariaCurrentValue = "page",
    children,
    class: className,
    custom,
    disabled,
    exact,
    external,
    href,
    inactiveClass,
    noRel,
    raw,
    ref = $bindable(null),
    rel,
    target,
    to,
    type = "button",
    ui,
    ...attrs
  }: LinkProps = $props();

  const resolvedHref = $derived(to ?? href);

  const isExternal = $derived.by(() => {
    if (target === "_blank") return true;
    if (external) return true;
    if (!resolvedHref) return false;
    return hasProtocol(resolvedHref, { acceptRelative: true });
  });

  const hasTarget = $derived(!!target && target !== "_self");

  const resolvedRel = $derived.by(() => {
    if (noRel) return null;
    if (rel) return rel;
    if (isExternal || hasTarget) return "noopener noreferrer";
    return null;
  });

  const isActive = $derived.by(() => {
    if (active !== undefined) return active;
    return false;
  });

  const linkClass = $derived.by(() => {
    if (raw) return cx(className, isActive ? activeClass : inactiveClass);
    return cx(ui?.base, className, isActive ? activeClass : inactiveClass);
  });
</script>

{#if custom}
  {@render custom({
    active: isActive,
    class: linkClass,
    disabled,
    href: resolvedHref,
    isExternal,
    raw,
    ref,
    rel: resolvedRel,
    target: target || (isExternal ? "_blank" : undefined),
    type,
    ...attrs
  })}
{:else}
  <LinkBase
    active={isActive}
    class={linkClass}
    {disabled}
    href={resolvedHref}
    {isExternal}
    {raw}
    {ref}
    rel={resolvedRel}
    target={target || (isExternal ? "_blank" : undefined)}
    {type}
    {...attrs}
  >
    {@render children?.({ active: isActive })}
  </LinkBase>
{/if}

// packages/solid/src/base/inertia/link/link.tsx
import { type Component, splitProps } from "solid-js";

import { cx } from "#build/ui/utils";

import { hasProtocol } from "ufo";

import { Dynamic } from "@/utils/dynamic";

import type { LinkProps } from "./link.types";
import LinkBase from "./link-base";

const Link: Component<LinkProps> = (props) => {
  const [
    {
      ariaCurrentValue = "page",
      children,
      custom,
      href,
      raw,
      to,
      type = "button",
      ui,
      ...rootProps
    },
    attrs,
  ] = splitProps(props, [
    "active",
    "activeClass",
    "ariaCurrentValue",
    "children",
    "custom",
    "disabled",
    "external",
    "href",
    "inactiveClass",
    "noRel",
    "raw",
    "rel",
    "target",
    "to",
    "type",
    "ui",
  ]);

  const resolvedHref = to ?? href;

  const isExternal =
    rootProps.target === "_blank" ||
    rootProps.external ||
    (!!resolvedHref && hasProtocol(resolvedHref, { acceptRelative: true }));

  const resolvedRel = rootProps.noRel
    ? undefined
    : (rootProps.rel ?? (isExternal ? "noopener noreferrer" : undefined));

  const isActive = rootProps.active ?? false;

  const linkClass = raw
    ? cx(
        attrs.class,
        isActive ? rootProps.activeClass : rootProps.inactiveClass
      )
    : cx(
        ui?.base,
        attrs.class,
        isActive ? rootProps.activeClass : rootProps.inactiveClass
      );

  if (custom) {
    return (
      <Dynamic
        active={isActive}
        ariaCurrentValue={ariaCurrentValue}
        disabled={rootProps.disabled}
        href={resolvedHref}
        isExternal={isExternal}
        raw={raw}
        rel={resolvedRel}
        target={rootProps.target ?? (isExternal ? "_blank" : undefined)}
        type={type}
        {...attrs}
      >
        {children}
      </Dynamic>
    );
  }

  return (
    <LinkBase
      class={linkClass}
      disabled={rootProps.disabled}
      href={resolvedHref}
      isExternal={isExternal}
      raw={raw}
      rel={resolvedRel}
      target={rootProps.target ?? (isExternal ? "_blank" : undefined)}
      type={type}
      {...attrs}
    >
      <Dynamic active={isActive}>{children}</Dynamic>
    </LinkBase>
  );
};

export default Link;
