// packages/svelte/src/lib/plugins/color-mode.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";

  import type { Theme } from "@veehance/core/types";

  export interface ColorModeProps {
    children?: Snippet;
    value?: {
      defaultTheme?: Theme;
      disableTransition?: boolean;
      storageKey?: string;
    };
  }
</script>

<script lang="ts">
  import { ModeWatcher } from "mode-watcher";

  import appConfig from "#build/app.config";

  let { children, value }: ColorModeProps = $props();
</script>

<ModeWatcher
  defaultMode={value?.defaultTheme ?? (appConfig.colorMode ? "system" : "light")}
  track={appConfig.colorMode}
/>
{@render children?.()}

// packages/react/src/lib/plugins/color-mode.tsx
import type { Theme } from "@veehance/core/types";

import { ThemeProvider } from "next-themes";

import appConfig from "#build/app.config";

export interface ColorModeProps {
  children?: React.ReactNode;
  value?: {
    defaultTheme?: Theme;
    disableTransition?: boolean;
    storageKey?: string;
  };
}

export function ColorMode({ children, value }: ColorModeProps) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme={
        value?.defaultTheme ?? (appConfig.colorMode ? "system" : "light")
      }
      disableTransitionOnChange={value?.disableTransition ?? true}
      enableSystem={appConfig.colorMode}
      storageKey={value?.storageKey}
    >
      {children}
    </ThemeProvider>
  );
}

export default ColorMode;
