// packages/svelte/src/lib/elements/image/image.svelte
<script lang="ts">
  import { cx } from "#build/ui/utils";

  import { Image as RawImage } from "@unpic/svelte";

  import { Factory } from "$lib/elements/factory";

  import type { ImageProps } from "./image.types";

  let {
    alt = "",
    as = "img",
    asChild,
    aspectRatio,
    cdn,
    class: className,
    crossorigin,
    height,
    layout = "constrained",
    objectFit,
    operations,
    options,
    priority,
    ref = $bindable(null),
    raw = false,
    src,
    ui,
    width,
    ...attrs
  }: ImageProps = $props();
</script>

{#if src && !asChild && !raw}
  <RawImage
    {...attrs}
    {alt}
    {aspectRatio}
    {cdn}
    class={cx(ui?.base, className)}
    {crossorigin}
    data-scope="image"
    {height}
    {layout}
    {objectFit}
    {operations}
    {options}
    {priority}
    {ref}
    {src}
    {width}
  />
{:else}
  <Factory
    {...attrs}
    {alt}
    {as}
    {asChild}
    class={cx(ui?.base, className)}
    {crossorigin}
    data-scope="image"
    {height}
    {ref}
    {src}
    {width}
  />
{/if}

// packages/react/src/base/next/image/image.tsx
import { forwardRef } from "react";

import { cx } from "#build/ui/utils";

import { Image as RawImage } from "@unpic/react/nextjs";

import { Factory } from "@/elements/factory";

import type { ImageProps } from "./image.types";

const Image = forwardRef<HTMLImageElement, ImageProps>(
  (
    {
      alt = "",
      asChild,
      aspectRatio,
      className,
      crossOrigin,
      cdn,
      height,
      layout = "constrained",
      objectFit,
      operations,
      options,
      priority,
      raw = false,
      src,
      ui,
      width,
      ...attrs
    },
    ref
  ) => {
    if (src && !asChild && !raw)
      return (
        <RawImage
          alt={alt}
          aspectRatio={aspectRatio as number}
          className={cx(ui?.base, className)}
          crossOrigin={crossOrigin}
          data-scope="image"
          height={height as number}
          layout={layout}
          objectFit={objectFit}
          operations={operations}
          options={options}
          priority={priority}
          ref={ref}
          src={src}
          width={width as number}
          {...attrs}
        />
      );

    return (
      // biome-ignore lint/performance/noImgElement: safe_to_set
      <Factory.img
        alt={alt}
        asChild={asChild}
        className={cx(ui?.base, className)}
        crossOrigin={crossOrigin}
        data-scope="image"
        height={height}
        ref={ref}
        src={src}
        width={width}
        {...attrs}
      />
    );
  }
);

Image.displayName = "Image";

export default Image;
