// packages/react/src/lib/providers/locale/use-date-formatter.ts
"use client";

import { useMemo } from "react";

import { useLocale } from "#build/ui/imports";

import { DateFormatter } from "@internationalized/date";

export interface UseDateFormatterProps extends Intl.DateTimeFormatOptions {
  locale?: string;
}

export interface UseDateFormatterReturn extends DateFormatter {}

export function useDateFormatter(
  props: UseDateFormatterProps = {}
): UseDateFormatterReturn {
  const { code } = useLocale();
  const locale = props.locale ?? code;
  return useMemo(() => {
    const { locale: _, ...options } = props;
    return new DateFormatter(locale, options);
  }, [locale, props]);
}

// packages/solid/src/lib/providers/locale/use-date-formatter.ts
import { type Accessor, createMemo } from "solid-js";

import { useLocale } from "#build/ui/imports";
import type { MaybeAccessor } from "#build/ui/types";

import { DateFormatter } from "@internationalized/date";

import { runIfFn } from "@/utils/fn";

export interface UseDateFormatterProps extends Intl.DateTimeFormatOptions {
  locale?: string;
}

export interface UseDateFormatterReturn extends Accessor<DateFormatter> {}

export function useDateFormatter(
  props: MaybeAccessor<UseDateFormatterProps> = {}
): UseDateFormatterReturn {
  const { code } = useLocale();
  return createMemo(() => {
    const resolvedProps = runIfFn(props);
    const locale = resolvedProps.locale ?? code();
    const { locale: _, ...options } = resolvedProps;
    return new DateFormatter(locale, options);
  });
}
