// packages/react/src/lib/components/main/main.tsx
import { cn } from "@veehance/core/utils";

export interface MainProps extends React.ComponentProps<"main"> {}

function Main({ className, ...props }: MainProps) {
  return (
    <main
      className={cn("min-h-screen", className)}
      data-slot="main"
      {...props}
    />
  );
}

export default Main;

// packages/vue/src/lib/components/main/main.vue
<script lang="ts">
  import type { HTMLAttributes } from "vue";

  export interface MainProps {
    class?: HTMLAttributes["class"];
  }
</script>

<script setup lang="ts">
  import { cn } from "@veehance/core/utils";

  const props = defineProps<MainProps>();
</script>

<template>
  <main
    :class="cn('mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8', props.class)"
    data-slot="main"
  >
    <slot />
  </main>
</template>
