// packages/vue/src/base/elements/start/link/link-base.vue
<script lang="ts" setup>
  import { Link as RawLink } from "@tanstack/vue-router";
  import { isArray } from "radashi";

  import { Factory } from "@/elements/factory";

  import type { LinkBaseProps } from "./link.types";

  defineOptions({ inheritAttrs: false });

  const props = withDefaults(defineProps<LinkBaseProps>(), {
    type: "button",
  });

  function onClickWrapper(e: MouseEvent) {
    if (props.disabled) {
      e.stopPropagation();
      e.preventDefault();
      return;
    }

    if (props.onClick) {
      for (const onClick of isArray(props.onClick)
        ? props.onClick
        : [props.onClick]) {
        onClick(e);
      }
    }
  }
</script>

<template>
  <RawLink
    v-if="!!href && !isExternal && !disabled"
    :class="props.class"
    :data-active="active ? 'true' : undefined"
    :data-scope="raw ? undefined : 'link'"
    :href="href"
    v-bind="{ rel, target, ...$attrs }"
    @click="onClickWrapper"
  >
    <slot />
  </RawLink>
  <Factory.a
    v-else-if="href"
    :aria-disabled="disabled ? 'true' : undefined"
    :class="props.class"
    :data-active="active ? 'true' : undefined"
    :data-scope="raw ? undefined : 'link'"
    v-bind="{
      href: disabled ? undefined : href,
      rel: rel ? rel : undefined,
      role: disabled ? 'link' : undefined,
      tabindex: disabled ? -1 : undefined,
      target: target ? target : undefined,
      ...$attrs
    }"
    @click="onClickWrapper"
  >
    <slot />
  </Factory.a>
  <Factory.button
    v-else
    :class="props.class"
    :data-active="active ? 'true' : undefined"
    :data-scope="raw ? undefined : 'link'"
    v-bind="{ disabled, type, ...$attrs }"
    @click="onClickWrapper"
  >
    <slot />
  </Factory.button>
</template>

// packages/react/src/base/router/link/link-base.tsx
import { forwardRef, type MouseEvent, useCallback } from "react";

import { isArray } from "radashi";
import { Link as RawLink } from "react-router";

import { Factory } from "@/elements/factory";

import type { LinkBaseProps } from "./link.types";

const LinkBase = forwardRef<
  HTMLAnchorElement | HTMLButtonElement,
  LinkBaseProps & { children: React.ReactNode }
>(
  (
    {
      active,
      children,
      disabled,
      href,
      isExternal,
      onClick,
      raw,
      rel,
      target,
      type = "button",
      ...attrs
    },
    ref
  ) => {
    const onClickWrapper = useCallback(
      (e: MouseEvent<HTMLAnchorElement | HTMLButtonElement>) => {
        if (disabled) {
          e.preventDefault();
          e.stopPropagation();
          return;
        }

        if (onClick) {
          for (const handler of isArray(onClick) ? onClick : [onClick]) {
            handler(e as any);
          }
        }
      },
      [disabled, onClick]
    );

    if (href && !isExternal && !disabled) {
      return (
        <RawLink
          data-active={active ? "true" : undefined}
          data-scope={raw ? undefined : "link"}
          onClick={onClickWrapper as any}
          ref={ref as any}
          rel={rel as string}
          target={target as string}
          to={href}
          {...attrs}
        >
          {children}
        </RawLink>
      );
    }

    if (href) {
      return (
        <Factory.a
          aria-disabled={disabled ? true : undefined}
          data-active={active ? "true" : undefined}
          data-scope={raw ? undefined : "link"}
          href={disabled ? undefined : href}
          onClick={onClickWrapper}
          ref={ref as any}
          rel={rel as string}
          role={disabled ? "link" : undefined}
          tabIndex={disabled ? -1 : undefined}
          target={target as string}
          {...attrs}
        >
          {children}
        </Factory.a>
      );
    }

    return (
      <Factory.button
        {...attrs}
        data-scope={raw ? undefined : "link"}
        disabled={disabled}
        onClick={onClickWrapper}
        ref={ref as any}
        type={type}
      >
        {children}
      </Factory.button>
    );
  }
);

LinkBase.displayName = "LinkBase";

export default LinkBase;
