// packages/vue/src/lib/components/main/main.vue
<script lang="ts">
  import type { HTMLAttributes } from "vue";

  export interface MainProps {
    class?: HTMLAttributes["class"];
  }
</script>

<script setup lang="ts">
  import { cn } from "@veehance/core/utils";

  const props = defineProps<MainProps>();
</script>

<template>
  <main
    :class="cn('mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8', props.class)"
    data-slot="main"
  >
    <slot />
  </main>
</template>

// packages/svelte/src/lib/components/main/main.svelte
<script module lang="ts">
  import type { HTMLAttributes } from "svelte/elements";

  export interface MainProps extends HTMLAttributes<HTMLElement> {}
</script>

<script lang="ts">
  import { cn } from "@veehance/core/utils";

  let { children, class: className, ...props }: MainProps = $props();

  const mergedProps = $derived({
    ...props,
    class: cn("", className),
    "data-slot": "main",
  });
</script>

<main {...mergedProps}>{@render children?.()}</main>
