// packages/react/src/lib/providers/locale/locale.tsx
"use client";

import type { LocaleProviderProps } from "./locale.types";
import { LocaleContextProvider } from "./use-locale-context";

function LocaleProvider({ children, value }: LocaleProviderProps) {
  return (
    <LocaleContextProvider value={value!}>{children}</LocaleContextProvider>
  );
}

export default LocaleProvider;

// packages/svelte/src/lib/providers/locale/locale.svelte
<script lang="ts">
  import type { LocaleProviderProps } from "./locale.types";
  import { LocaleContextProvider } from "./use-locale-context";

  let { children, value }: LocaleProviderProps = $props();

  $effect(() => {
    LocaleContextProvider(() => value!);
  });
</script>

{@render children?.()}
