// packages/svelte/src/lib/components/color-mode/image/image.svelte
<script lang="ts">
  import { Image } from "#build/ui/components";
  import { cc, cn } from "#build/ui/utils";

  import type { ColorModeImageProps } from "./image.types";

  let {
    class: className,
    light,
    dark,
    ref = $bindable(null),
    ui,
    ...attrs
  }: ColorModeImageProps = $props();
</script>

<Image
  class={cn(cc('dark:hidden'), ui?.base, className)}
  {ref}
  src={light}
  {...attrs}
/>
<Image
  class={cn(cc('hidden dark:inline-block'), ui?.base, className)}
  {ref}
  src={dark}
  {...attrs}
/>

// packages/vue/src/lib/components/color-mode/image/image.vue
<script lang="ts" setup>
  import { Image } from "#build/ui/components";
  import { useForwardExpose } from "#build/ui/imports";
  import { cc, cx } from "#build/ui/utils";

  import type { ColorModeImageProps } from "./image.types";

  defineOptions({ inheritAttrs: false });

  const props = defineProps<ColorModeImageProps>();

  useForwardExpose();
</script>

<template>
  <Image
    :class="cx(cc('dark:hidden'), ui?.base, props.class)"
    :src="light"
    v-bind="$attrs"
  />
  <Image
    :class="cx(cc('hidden dark:inline-block'), ui?.base, props.class)"
    :src="dark"
    v-bind="$attrs"
  />
</template>
