// packages/react/src/lib/components/app/app.tsx
import type { RootNode } from "@veehance/core/types";

import { ColorMode, type ColorModeProps } from "../../plugins/color-mode.js";
import { Head, type HeadProps } from "../../plugins/head.js";
import { EnvironmentProvider } from "../../providers/environment/index.js";

export interface AppProps {
  children?: React.ReactNode;
  environment?: RootNode | (() => RootNode) | undefined;
  head?: HeadProps["value"];
  theme?: ColorModeProps["value"];
}

function App({ children, environment, head, theme }: AppProps) {
  return (
    <EnvironmentProvider value={environment}>
      <Head value={head}>
        <ColorMode value={theme}>{children}</ColorMode>
      </Head>
    </EnvironmentProvider>
  );
}

export default App;

// packages/svelte/src/lib/components/app/app.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";

  import type { RootNode } from "@veehance/core/types";
  import type { ColorModeProps } from "../../plugins/color-mode.svelte";

  export interface AppProps {
    children?: Snippet;
    environment?: RootNode | (() => RootNode) | undefined;
    theme?: ColorModeProps["value"];
  }
</script>

<script lang="ts">
  import { default as ColorMode } from "../../plugins/color-mode.svelte";
  import { EnvironmentProvider } from "../../providers/environment/index.js";

  let { children, environment, theme }: AppProps = $props();
</script>

<EnvironmentProvider value={environment}>
  <ColorMode value={theme}> {@render children?.()} </ColorMode>
</EnvironmentProvider>
