// packages/vue/src/lib/components/container/container.vue
<script lang="ts">
  import type { HTMLAttributes } from "vue";

  export interface ContainerProps {
    class?: HTMLAttributes["class"];
  }
</script>

<script setup lang="ts">
  import { cn } from "@veehance/core/utils";

  const props = defineProps<ContainerProps>();
</script>

<template>
  <div
    :class="cn('mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8', props.class)"
    data-slot="container"
  >
    <slot />
  </div>
</template>

// packages/react/src/lib/components/container/container.tsx
import { cn } from "@veehance/core/utils";

export interface ContainerProps extends React.ComponentProps<"div"> {}

function Container({ className, ...props }: ContainerProps) {
  return (
    <div
      className={cn("mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8", className)}
      data-slot="container"
      {...props}
    />
  );
}

export default Container;
