// packages/react/src/lib/providers/keyboard/use-hotkey-recorder.ts
/** biome-ignore-all lint/complexity/noVoid: safe_to_Set */
"use client";

import {
  useCallback,
  useMemo,
  useRef,
  useState,
  useSyncExternalStore,
} from "react";

import {
  useEnvironment,
  useEvent,
  useSafeLayoutEffect,
} from "#build/ui/imports";

import {
  createHotkeyRecorder,
  type HotkeyRecorderOptions,
  type RecordedHotkey,
} from "@zag-js/hotkeys";

export interface UseHotkeyRecorderProps
  extends Omit<HotkeyRecorderOptions, "target"> {}

export interface UseHotkeyRecorderReturn {
  cancel: () => void;
  clear: () => void;
  recording: boolean;
  start: () => void;
  stop: () => void;
  value: RecordedHotkey | null;
}

export const useHotkeyRecorder = (
  props: UseHotkeyRecorderProps = {}
): UseHotkeyRecorderReturn => {
  const { formatOptions, sequenceTimeoutMs } = props;

  const { getRootNode } = useEnvironment();
  const [recorder] = useState(() => createHotkeyRecorder());

  const onRecord = useEvent(props.onRecord);
  const onCancel = useEvent(props.onCancel);
  const onClear = useEvent(props.onClear);

  useSafeLayoutEffect(() => {
    recorder.init(getRootNode() as Document);
    recorder.setOptions({ onCancel, onClear, onRecord });
    return () => {
      recorder.destroy();
    };
  }, [recorder, getRootNode, onRecord, onCancel, onClear]);

  const formatRef = useRef(formatOptions);
  formatRef.current = formatOptions;

  const formatKey = formatOptions ? JSON.stringify(formatOptions) : "";

  useSafeLayoutEffect(() => {
    recorder.setOptions({
      ...(formatRef.current && { formatOptions: formatRef.current }),
      ...(sequenceTimeoutMs !== undefined && { sequenceTimeoutMs }),
    });
  }, [recorder, formatKey, sequenceTimeoutMs]);

  const subscribe = useCallback(
    (onChange: () => void) => recorder.subscribe(onChange),
    [recorder]
  );
  const getSnapshot = useCallback(() => recorder.getState(), [recorder]);

  const state = useSyncExternalStore(subscribe, getSnapshot, getSnapshot);

  return useMemo(
    () => ({
      cancel: () => void recorder.cancel(),
      clear: () => void recorder.clear(),
      recording: state.recording,
      start: () => void recorder.start(),
      stop: () => void recorder.stop(),
      value: state.value,
    }),
    [state, recorder]
  );
};

// packages/solid/src/lib/providers/keyboard/use-hotkey-recorder.ts
/** biome-ignore-all lint/complexity/noVoid: safe_to_set */
import { onCleanup, onMount } from "solid-js";

import { useEnvironment } from "#build/ui/imports";
import type { Accessor, MaybeAccessor } from "#build/ui/types";

import {
  createHotkeyRecorder,
  type HotkeyRecorderOptions,
  type HotkeyRecorderState,
} from "@zag-js/hotkeys";
import { useSyncExternalStore } from "@zag-js/solid";

import { runIfFn } from "@/utils/fn";

export interface UseHotkeyRecorderProps
  extends Omit<HotkeyRecorderOptions, "target"> {}

export interface UseHotkeyRecorderReturn {
  cancel: () => void;
  clear: () => void;
  start: () => void;
  state: Accessor<HotkeyRecorderState>;
  stop: () => void;
}

export const useHotkeyRecorder = (
  props: MaybeAccessor<UseHotkeyRecorderProps> = {}
): UseHotkeyRecorderReturn => {
  const { getRootNode } = useEnvironment();
  const recorder = createHotkeyRecorder();

  onMount(() => {
    const options = runIfFn(props);

    recorder.init(getRootNode() as Document);
    recorder.setOptions({
      onCancel: () => runIfFn(props).onCancel?.(),
      onClear: () => runIfFn(props).onClear?.(),
      onRecord: (hotkey) => runIfFn(props).onRecord?.(hotkey),
      ...(options.formatOptions && { formatOptions: options.formatOptions }),
      ...(options.sequenceTimeoutMs !== undefined && {
        sequenceTimeoutMs: options.sequenceTimeoutMs,
      }),
    });

    onCleanup(() => recorder.destroy());
  });

  const state = useSyncExternalStore(
    (listener) => recorder.subscribe(listener),
    () => recorder.getState()
  );

  return {
    cancel: () => void recorder.cancel(),
    clear: () => void recorder.clear(),
    start: () => void recorder.start(),
    state,
    stop: () => void recorder.stop(),
  };
};
