// packages/svelte/src/lib/providers/color-mode/examples/setup.svelte
<script lang="ts">
  import { ColorModeProvider } from "@veehance/svelte/color-mode";
  import { EnvironmentProvider } from "@veehance/svelte/environment";
</script>

<iframe title="IFrame Context">
  <EnvironmentProvider>
    <ColorModeProvider><!-- Your App --></ColorModeProvider>
  </EnvironmentProvider>
</iframe>

// packages/solid/src/lib/providers/color-mode/examples/setup.tsx
import { ColorModeProvider } from "@veehance/solid/color-mode";
import { EnvironmentProvider } from "@veehance/solid/environment";

export default () => {
  return (
    <iframe title="IFrame Context">
      <EnvironmentProvider>
        <ColorModeProvider>{/* Your App */}</ColorModeProvider>
      </EnvironmentProvider>
    </iframe>
  );
};
