// packages/vue/src/lib/providers/environment/environment.vue
<script lang="ts" setup>
  import { computed, ref } from "vue";

  import { getDocument, getWindow } from "@zag-js/dom-query";

  import { runIfFn } from "@/utils/fn.js";

  import type { EnvironmentProviderProps } from "./environment.types";
  import { EnvironmentContextProvider } from "./use-environment-context";

  const props = defineProps<EnvironmentProviderProps>();
  const spanRef = ref<HTMLSpanElement | null>(null);

  const getRootNode = () =>
    runIfFn(props.value) ?? spanRef.value?.getRootNode() ?? document;

  const environment = computed(() => ({
    getDocument: () => getDocument(getRootNode()),
    getRootNode,
    getWindow: () => getWindow(getRootNode()),
  }));

  EnvironmentContextProvider(environment);
</script>

<template>
  <slot />
  <span hidden v-if="!props.value" ref="spanRef"></span>
</template>

// packages/svelte/src/lib/providers/environment/environment.svelte
<script lang="ts">
  import { getDocument, getWindow } from "@zag-js/dom-query";

  import { runIfFn } from "$lib/utils/fn";

  import type {
    EnvironmentContext,
    EnvironmentProviderProps,
  } from "./environment.types";
  import { EnvironmentContextProvider } from "./use-environment-context";

  const { value, children }: EnvironmentProviderProps = $props();
  let spanRef: HTMLSpanElement | null = $state(null);

  const getRootNode = () =>
    runIfFn(value) ?? spanRef?.ownerDocument ?? document;

  const environment = $derived<ReturnType<EnvironmentContext>>({
    getDocument: () => getDocument(getRootNode()),
    getRootNode,
    getWindow: () => getWindow(getRootNode()),
  });

  EnvironmentContextProvider(() => environment);
</script>

{@render children?.()}
{#if !value}
  <span hidden bind:this={spanRef}></span>
{/if}
