// packages/solid/src/lib/composables/use-controllable-state.ts
/** biome-ignore-all lint/complexity/noBannedTypes: safe_to_set */
import { type Accessor, createMemo, createSignal, untrack } from "solid-js";

import { runIfFn } from "@/utils/fn.js";

export interface UseControllableStateProps<T> {
  defaultValue?: Accessor<T | undefined> | T;
  onChange?: (value: T) => void;
  value?: Accessor<T | undefined>;
}

export function useControllableState<T>(props: UseControllableStateProps<T>) {
  const [uncontrolledValue, setUncontrolledValue] = createSignal(
    runIfFn(props.defaultValue)
  );
  const controlled = createMemo(() => props.value?.() !== undefined);

  const currentValue = createMemo(() =>
    controlled() ? props.value?.() : uncontrolledValue()
  );

  const setValue = (next: Exclude<T, Function> | ((prev: T) => T)) => {
    untrack(() => {
      const nextValue = runIfFn(next, currentValue() as T);
      if (controlled()) return props.onChange?.(nextValue);

      setUncontrolledValue(nextValue as Exclude<T, Function>);
      return props.onChange?.(nextValue);
    });
  };

  return [currentValue as Accessor<T>, setValue] as const;
}

// packages/react/src/lib/composables/use-controllable-state.ts
"use client";

import { useCallback, useState } from "react";

export interface UseControllableStateProps<T> {
  defaultValue?: T | undefined;
  onChange?: ((value: T) => void) | undefined;
  value?: T | undefined;
}

export function useControllableState<T>(props: UseControllableStateProps<T>) {
  const { value, onChange, defaultValue } = props;

  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue);

  const controlled = value !== undefined;
  const currentValue = controlled ? value : uncontrolledValue;

  const setValue = useCallback(
    (v: T) => {
      if (controlled) return onChange?.(v);
      setUncontrolledValue(v);
      return onChange?.(v);
    },
    [controlled, onChange]
  );

  return [currentValue as T, setValue] as const;
}
