// packages/react/src/lib/providers/app/app.tsx
"use client";

import { ColorModeProvider } from "../color-mode";
import { EnvironmentProvider } from "../environment";
import { LocaleProvider } from "../locale";
import type { AppProviderProps } from "./app.types";

function AppProvider({
  children,
  colorMode,
  environment,
  locale,
}: AppProviderProps) {
  return (
    <EnvironmentProvider value={environment}>
      <LocaleProvider value={locale}>
        <ColorModeProvider value={colorMode}>{children}</ColorModeProvider>
      </LocaleProvider>
    </EnvironmentProvider>
  );
}

export default AppProvider;

// packages/svelte/src/lib/providers/app/app.svelte
<script lang="ts">
  import { ColorModeProvider } from "../color-mode";
  import { EnvironmentProvider } from "../environment";
  import { LocaleProvider } from "../locale";
  import type { AppProviderProps } from "./app.types";

  const { environment, locale, colorMode, children }: AppProviderProps =
    $props();
</script>

<EnvironmentProvider value={environment}>
  <LocaleProvider value={locale}>
    <ColorModeProvider value={colorMode}>
      {@render children?.()}
    </ColorModeProvider>
  </LocaleProvider>
</EnvironmentProvider>
