// packages/vue/src/lib/providers/app/app.vue
<script lang="ts" setup>
  import { ColorModeProvider } from "../color-mode";
  import { EnvironmentProvider } from "../environment";
  import { LocaleProvider } from "../locale";
  import type { AppProviderProps } from "./app.types";

  const props = defineProps<AppProviderProps>();
</script>

<template>
  <EnvironmentProvider :value="props.environment">
    <LocaleProvider :value="props.locale">
      <ColorModeProvider :value="props.colorMode">
        <slot />
      </ColorModeProvider>
    </LocaleProvider>
  </EnvironmentProvider>
</template>

// packages/svelte/src/lib/providers/app/app.svelte
<script lang="ts">
  import { ColorModeProvider } from "../color-mode";
  import { EnvironmentProvider } from "../environment";
  import { LocaleProvider } from "../locale";
  import type { AppProviderProps } from "./app.types";

  const { environment, locale, colorMode, children }: AppProviderProps =
    $props();
</script>

<EnvironmentProvider value={environment}>
  <LocaleProvider value={locale}>
    <ColorModeProvider value={colorMode}>
      {@render children?.()}
    </ColorModeProvider>
  </LocaleProvider>
</EnvironmentProvider>
