// packages/react/src/lib/providers/color-mode/color-mode-script.tsx
import { createColorScript, resolveColorScript } from "@veehance/core/utils/script";

import appConfig from "#build/app.config";

import type { ColorModeValue } from "./color-mode.types.js";

export function ColorModeScript({ ...value }: ColorModeValue) {
  const script = createColorScript(
    resolveColorScript(value, appConfig.colorMode)
  );

  return (
    <script
      // biome-ignore lint/security/noDangerouslySetInnerHtml: safe to set
      dangerouslySetInnerHTML={{ __html: script }}
      suppressHydrationWarning
    />
  );
}

// packages/svelte/src/lib/providers/color-mode/color-mode-script.svelte
<script lang="ts">
  import {
    createColorScript,
    resolveColorScript,
  } from "@veehance/core/utils/script";

  import appConfig from "#build/app.config";

  import type { ColorModeValue } from "./color-mode.types.js";

  let value: ColorModeValue = $props();

  const script = $derived(
    createColorScript(resolveColorScript(value, appConfig.colorMode))
  );
</script>

<svelte:head> {@html `<script>${script}</script>`} </svelte:head>
