// packages/solid/src/lib/providers/environment/environment.tsx
import { createMemo, createSignal, Show } from "solid-js";

import { getDocument, getWindow } from "@zag-js/dom-query";

import { runIfFn } from "@/utils/fn";

import type { EnvironmentProviderProps } from "./environment.types";
import { EnvironmentContextProvider } from "./use-environment-context";

function EnvironmentProvider(props: EnvironmentProviderProps) {
  const [spanRef, setSpanRef] = createSignal<HTMLSpanElement>();
  const getRootNode = () =>
    runIfFn(props.value) ?? spanRef()?.getRootNode() ?? document;

  const environment = createMemo(() => ({
    getDocument: () => getDocument(getRootNode()),
    getRootNode,
    getWindow: () => getWindow(getRootNode()),
  }));

  return (
    <EnvironmentContextProvider value={environment}>
      {props.children}
      <Show when={!props.value}>
        <span hidden ref={setSpanRef} />
      </Show>
    </EnvironmentContextProvider>
  );
}

export default EnvironmentProvider;

// packages/react/src/lib/providers/environment/environment.tsx
"use client";

import { useMemo, useState } from "react";

import { getDocument, getWindow } from "@zag-js/dom-query";

import { runIfFn } from "@/utils/fn";

import type { EnvironmentProviderProps } from "./environment.types";
import { EnvironmentContextProvider } from "./use-environment-context";

function EnvironmentProvider(props: EnvironmentProviderProps) {
  const { value, children } = props;
  const [spanRef, setSpanRef] = useState<HTMLSpanElement | null>();

  const getRootNode = useMemo(
    () => () => runIfFn(value) ?? spanRef?.getRootNode() ?? document,
    [value, spanRef]
  );

  const environment = useMemo(
    () => ({
      getDocument: () => getDocument(getRootNode()),
      getRootNode,
      getWindow: () => getWindow(getRootNode()),
    }),
    [getRootNode]
  );

  return (
    <EnvironmentContextProvider value={environment}>
      {children}
      {!value && <span hidden ref={setSpanRef} />}
    </EnvironmentContextProvider>
  );
}

export default EnvironmentProvider;
