// packages/svelte/src/lib/components/container/container.svelte
<script module lang="ts">
  import type { HTMLAttributes } from "svelte/elements";

  export interface ContainerProps extends HTMLAttributes<HTMLDivElement> {}
</script>

<script lang="ts">
  import { cn } from "@veehance/core/utils";

  let { children, class: className, ...props }: ContainerProps = $props();

  const mergedProps = $derived({
    ...props,
    class: cn("", className),
    "data-slot": "container",
  });
</script>

<div {...mergedProps}>{@render children?.()}</div>

// packages/vue/src/lib/components/container/container.vue
<script lang="ts">
  import type { HTMLAttributes } from "vue";

  export interface ContainerProps {
    class?: HTMLAttributes["class"];
  }
</script>

<script setup lang="ts">
  import { cn } from "@veehance/core/utils";

  const props = defineProps<ContainerProps>();
</script>

<template>
  <div
    :class="cn('mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8', props.class)"
    data-slot="container"
  >
    <slot />
  </div>
</template>
