// packages/react/src/lib/providers/environment/environment.tsx
"use client";

import { useMemo, useState } from "react";

import { getDocument, getWindow } from "@zag-js/dom-query";

import { runIfFn } from "@/utils/fn";

import type { EnvironmentProviderProps } from "./environment.types";
import { EnvironmentContextProvider } from "./use-environment-context";

function EnvironmentProvider(props: EnvironmentProviderProps) {
  const { value, children } = props;
  const [spanRef, setSpanRef] = useState<HTMLSpanElement | null>();

  const getRootNode = useMemo(
    () => () => runIfFn(value) ?? spanRef?.getRootNode() ?? document,
    [value, spanRef]
  );

  const environment = useMemo(
    () => ({
      getDocument: () => getDocument(getRootNode()),
      getRootNode,
      getWindow: () => getWindow(getRootNode()),
    }),
    [getRootNode]
  );

  return (
    <EnvironmentContextProvider value={environment}>
      {children}
      {!value && <span hidden ref={setSpanRef} />}
    </EnvironmentContextProvider>
  );
}

export default EnvironmentProvider;

// packages/vue/src/lib/providers/environment/environment.vue
<script lang="ts" setup>
  import { computed, ref } from "vue";

  import { getDocument, getWindow } from "@zag-js/dom-query";

  import { runIfFn } from "@/utils/fn.js";

  import type { EnvironmentProviderProps } from "./environment.types";
  import { EnvironmentContextProvider } from "./use-environment-context";

  const props = defineProps<EnvironmentProviderProps>();
  const spanRef = ref<HTMLSpanElement | null>(null);

  const getRootNode = () =>
    runIfFn(props.value) ?? spanRef.value?.getRootNode() ?? document;

  const environment = computed(() => ({
    getDocument: () => getDocument(getRootNode()),
    getRootNode,
    getWindow: () => getWindow(getRootNode()),
  }));

  EnvironmentContextProvider(environment);
</script>

<template>
  <slot />
  <span hidden v-if="!props.value" ref="spanRef"></span>
</template>
