// packages/react/src/lib/providers/environment/environment-provider.tsx
"use client";

import { type ReactNode, useMemo, useState } from "react";

import type { RootNode } from "@veehance/core/types";
import { getDocument, getWindow } from "@veehance/core/utils";

import { runIfFn } from "../../utils/run-if-fn.js";
import { EnvironmentContextProvider } from "./use-environment-context.js";

export interface EnvironmentProviderProps {
  children?: ReactNode | undefined;
  value?: RootNode | (() => RootNode) | undefined;
}

function EnvironmentProvider(props: EnvironmentProviderProps) {
  const { value, children } = props;
  const [spanRef, setSpanRef] = useState<HTMLSpanElement | null>();

  const getRootNode = useMemo(
    () => () => runIfFn(value) ?? spanRef?.getRootNode() ?? document,
    [value, spanRef]
  );

  const environment = useMemo(
    () => ({
      getRootNode,
      getWindow: () => getWindow(getRootNode()),
      getDocument: () => getDocument(getRootNode()),
    }),
    [getRootNode]
  );

  return (
    <EnvironmentContextProvider value={environment}>
      {children}
      {!value && <span hidden ref={setSpanRef} />}
    </EnvironmentContextProvider>
  );
}

export default EnvironmentProvider;

// packages/vue/src/lib/providers/environment/environment-provider.vue
<script setup lang="ts">
  import { computed, ref } from "vue";

  import type { RootNode } from "@veehance/core/types";
  import { getDocument, getWindow } from "@veehance/core/utils";

  import { runIfFn } from "../../utils/run-if-fn.js";
  import { EnvironmentContextProvider } from "./use-environment-context.js";

  export interface EnvironmentProviderProps {
    value?: RootNode | (() => RootNode);
  }

  const props = defineProps<EnvironmentProviderProps>();
  const spanRef = ref<HTMLSpanElement | null>(null);

  const getRootNode = () =>
    runIfFn(props.value) ?? spanRef.value?.getRootNode() ?? document;

  const environment = computed(() => ({
    getRootNode,
    getDocument: () => getDocument(getRootNode()),
    getWindow: () => getWindow(getRootNode()),
  }));

  EnvironmentContextProvider(environment);
</script>

<template>
  <slot />
  <span v-if="!props.value" hidden ref="spanRef"></span>
</template>
