// packages/svelte/src/lib/providers/environment/environment-provider.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";

  import type { MaybeFunction, RootNode } from "@veehance/core/types";
  import { getDocument, getWindow } from "@veehance/core/utils";

  import type { UseEnvironmentContext } from "./use-environment-context.js";

  export interface EnvironmentProviderProps {
    children?: Snippet;
    value?: MaybeFunction<RootNode>;
  }
</script>

<script lang="ts">
  import { runIfFn } from "../../utils/run-if-fn.js";
  import { EnvironmentContextProvider } from "./use-environment-context.js";

  const { value, children }: EnvironmentProviderProps = $props();
  let spanRef: HTMLSpanElement | null = $state(null);

  const getRootNode = () =>
    runIfFn(value) ?? spanRef?.ownerDocument ?? document;

  const environment = $derived<ReturnType<UseEnvironmentContext>>({
    getRootNode,
    getDocument: () => getDocument(getRootNode()),
    getWindow: () => getWindow(getRootNode()),
  });

  EnvironmentContextProvider(() => environment);
</script>

{@render children?.()}
{#if !value}
  <span bind:this={spanRef} hidden></span>
{/if}

// packages/vue/src/lib/providers/environment/environment-provider.vue
<script setup lang="ts">
  import { computed, ref } from "vue";

  import type { RootNode } from "@veehance/core/types";
  import { getDocument, getWindow } from "@veehance/core/utils";

  import { runIfFn } from "../../utils/run-if-fn.js";
  import { EnvironmentContextProvider } from "./use-environment-context.js";

  export interface EnvironmentProviderProps {
    value?: RootNode | (() => RootNode);
  }

  const props = defineProps<EnvironmentProviderProps>();
  const spanRef = ref<HTMLSpanElement | null>(null);

  const getRootNode = () =>
    runIfFn(props.value) ?? spanRef.value?.getRootNode() ?? document;

  const environment = computed(() => ({
    getRootNode,
    getDocument: () => getDocument(getRootNode()),
    getWindow: () => getWindow(getRootNode()),
  }));

  EnvironmentContextProvider(environment);
</script>

<template>
  <slot />
  <span v-if="!props.value" hidden ref="spanRef"></span>
</template>
