// packages/react/src/lib/components/prose/h3/h3.tsx
import { forwardRef } from "react";

import { Factory } from "#build/ui/components";
import { useAppConfig } from "#build/ui/imports";
import { cx } from "#build/ui/utils";

import type { ProseH3Props } from "./h3.types";

const ProseH3 = forwardRef<HTMLHeadingElement, ProseH3Props>(
  ({ anchor, children, className, id, ...attrs }, ref) => {
    const appConfig = useAppConfig() as {
      prose?: { headings?: { anchorLinks?: { h3?: boolean } } };
    };

    const generate =
      id && (anchor ?? appConfig.prose?.headings?.anchorLinks?.h3 ?? false);

    return (
      <Factory.h3 {...attrs} className={cx(className)} id={id} ref={ref}>
        {/** biome-ignore lint/suspicious/noLeakedRender: safe_to_set */}
        {generate ? <a href={`#${id}`}>{children}</a> : children}
      </Factory.h3>
    );
  }
);

ProseH3.displayName = "ProseH3";

export default ProseH3;

// packages/svelte/src/lib/components/prose/h3/h3.svelte
<script lang="ts">
  import { Factory } from "#build/ui/components";
  import { useAppConfig } from "#build/ui/imports";
  import { cx } from "#build/ui/utils";

  import type { ProseH3Props } from "./h3.types";

  let {
    as = "h3",
    anchor,
    children,
    class: className,
    id,
    ref = $bindable(null),
    ui,
    ...attrs
  }: ProseH3Props = $props();

  const appConfig = useAppConfig() as {
    prose?: { headings?: { anchorLinks?: { h3?: boolean } } };
  };

  const generate = $derived(
    () => id && (anchor ?? appConfig.prose?.headings?.anchorLinks?.h3 ?? false)
  );
</script>

<Factory {...attrs} {as} class={cx(className)} {id}>
  {#if id && generate()}
    <a href={`#${id}`}> {@render children?.()} </a>
  {:else}
    {@render children?.()}
  {/if}
</Factory>
