// packages/solid/src/lib/components/ui/main/main.tsx
import { type ComponentProps, splitProps } from "solid-js";

import { ui as theme } from "@iueev/core/theme";
import { cv } from "@iueev/core/utils";

import type { MainTheme } from "./main.types";

export interface MainProps extends ComponentProps<"main"> {
  ui?: MainTheme["slots"];
}

function Main(props: MainProps) {
  const [{ children, ui: overrides }, attrs] = splitProps(props, [
    "children",
    "ui",
  ]);
  const ui = cv(theme.main);
  return (
    <main
      class={ui({ className: [overrides?.base, props.class] })}
      data-scope="main"
      {...attrs}
    >
      {children}
    </main>
  );
}

export default Main;

// packages/react/src/lib/components/ui/main/main.tsx
import { ui as theme } from "@iueev/core/theme";
import { cv } from "@iueev/core/utils";

import type { MainTheme } from "./main.types";

export interface MainProps extends React.ComponentProps<"main"> {
  ui?: MainTheme["slots"];
}

function Main({ className, ui: overrides, ...props }: MainProps) {
  const ui = cv(theme.main);
  return (
    <main
      className={ui({ className: [overrides?.base, className] })}
      data-scope="main"
      {...props}
    />
  );
}

export default Main;
